# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import qa_pb2 as qa__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QAServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Answer = channel.unary_unary(
                '/qa.QAServer/Answer',
                request_serializer=qa__pb2.Question.SerializeToString,
                response_deserializer=qa__pb2.AnswerResponse.FromString,
                _registered_method=True)


class QAServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QAServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Answer': grpc.unary_unary_rpc_method_handler(
                    servicer.Answer,
                    request_deserializer=qa__pb2.Question.FromString,
                    response_serializer=qa__pb2.AnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qa.QAServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qa.QAServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QAServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qa.QAServer/Answer',
            qa__pb2.Question.SerializeToString,
            qa__pb2.AnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
