FROM python:3.10-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1


COPY evaluate/evaluate_quick.py /app/evaluate_quick.py
COPY evaluate/qa_pb2.py /app/qa_pb2.py
COPY evaluate/qa_pb2_grpc.py /app/qa_pb2_grpc.py


RUN pip install --no-cache-dir \
    grpcio pandas numpy tqdm chromadb sentence-transformers

RUN mkdir -p /data/results_quick

CMD ["python", "/app/evaluate_quick.py"]
